// This file is auto-generated by @hey-api/openapi-ts

export { getProducts, getProductsStats, type Options } from './sdk.gen';
export type { ClientOptions, ErrorResponse, GetProductsData, GetProductsError, GetProductsErrors, GetProductsResponse, GetProductsResponses, GetProductsStatsData, GetProductsStatsResponse, GetProductsStatsResponses, Product, ProductsResponse, ProductStatsResponse } from './types.gen';
