// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetProductsData, GetProductsErrors, GetProductsResponses, GetProductsStatsData, GetProductsStatsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 상품 상태별 통계
 */
export const getProductsStats = <ThrowOnError extends boolean = false>(options?: Options<GetProductsStatsData, ThrowOnError>) => (options?.client ?? client).get<GetProductsStatsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/products/stats',
    ...options
});

/**
 * 상품 목록 (페이지네이션)
 */
export const getProducts = <ThrowOnError extends boolean = false>(options?: Options<GetProductsData, ThrowOnError>) => (options?.client ?? client).get<GetProductsResponses, GetProductsErrors, ThrowOnError>({
    responseType: 'json',
    url: '/products',
    ...options
});
