// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};

export type ProductStatsResponse = {
    total: number;
    selling: number;
    outOfStock: number;
    discontinued: number;
};

export type ProductsResponse = {
    items: Array<Product>;
    total: number;
    page: number;
    pageSize: number;
};

export type Product = {
    id: number;
    name: string;
    category: string;
    price: number;
    stock: number;
    status: 'SELLING' | 'OUT_OF_STOCK' | 'DISCONTINUED';
    createdAt: string;
};

export type ErrorResponse = {
    error: string;
};

export type GetProductsStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/stats';
};

export type GetProductsStatsResponses = {
    /**
     * 상태별 상품 수
     */
    200: ProductStatsResponse;
};

export type GetProductsStatsResponse = GetProductsStatsResponses[keyof GetProductsStatsResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        pageSize?: number;
    };
    url: '/products';
};

export type GetProductsErrors = {
    /**
     * 잘못된 쿼리 파라미터
     */
    400: ErrorResponse;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * 상품 목록
     */
    200: ProductsResponse;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];
