// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getProducts, getProductsStats, type Options } from '../sdk.gen';
import type { GetProductsData, GetProductsError, GetProductsResponse, GetProductsStatsData, GetProductsStatsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getProductsStatsQueryKey = (options?: Options<GetProductsStatsData>) => createQueryKey('getProductsStats', options);

/**
 * 상품 상태별 통계
 */
export const getProductsStatsOptions = (options?: Options<GetProductsStatsData>) => queryOptions<GetProductsStatsResponse, AxiosError<DefaultError>, GetProductsStatsResponse, ReturnType<typeof getProductsStatsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProductsStats({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsStatsQueryKey(options)
});

export const getProductsQueryKey = (options?: Options<GetProductsData>) => createQueryKey('getProducts', options);

/**
 * 상품 목록 (페이지네이션)
 */
export const getProductsOptions = (options?: Options<GetProductsData>) => queryOptions<GetProductsResponse, AxiosError<GetProductsError>, GetProductsResponse, ReturnType<typeof getProductsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getProducts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getProductsInfiniteQueryKey = (options?: Options<GetProductsData>): QueryKey<Options<GetProductsData>> => createQueryKey('getProducts', options, true);

/**
 * 상품 목록 (페이지네이션)
 */
export const getProductsInfiniteOptions = (options?: Options<GetProductsData>) => infiniteQueryOptions<GetProductsResponse, AxiosError<GetProductsError>, InfiniteData<GetProductsResponse>, QueryKey<Options<GetProductsData>>, number | Pick<QueryKey<Options<GetProductsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetProductsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getProducts({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getProductsInfiniteQueryKey(options)
});
